---
title: "Les triathlons de La Bergerie"
editor_options: 
  chunk_output_type: inline
---

Bienvenue sur le site web de la bergerie.

Voici le tableau récapitulatif de nos derniers triathlons :

```{r, include = FALSE}

library(readxl)
library(kableExtra)
library(tidyverse)

df_triathlon <- read_excel("links/triathlon.xlsx") %>%
  mutate(
    Pourc = ifelse(is.na(Pourc), NA, 
                   round(Pourc, 0)),
    t_nat = ifelse(is.na(t_nat), NA, 
                   format(as.POSIXct(t_nat, format="%H:%M:%S"), "%H:%M:%S")),
    all_nat = ifelse(is.na(all_nat), NA,
                     format(as.POSIXct(all_nat, format="%H:%M:%S"), "%H:%M:%S")),
    tran1 = ifelse(is.na(tran1), NA, 
                   format(as.POSIXct(tran1, format="%H:%M:%S"), "%H:%M:%S")),
    t_cyc = ifelse(is.na(t_cyc), NA, 
                   format(as.POSIXct(t_cyc, format="%H:%M:%S"), "%H:%M:%S")),
    all_cyc = ifelse(is.na(all_cyc), NA, 
                     round(all_cyc, 2)),
    tran2 = ifelse(is.na(tran2), NA,
                   format(as.POSIXct(tran2, format="%H:%M:%S"), "%H:%M:%S")),
    t_cap = ifelse(is.na(t_cap), NA, 
                   format(as.POSIXct(t_cap, format="%H:%M:%S"), "%H:%M:%S")),
    all_cap = ifelse(is.na(all_cap), NA, 
                     format(as.POSIXct(all_cap, format="%H:%M:%S"), "%H:%M:%S")),
    temps_f_min = ifelse(is.na(as.Date(as.numeric(temps_f_min))), NA, 
                        format(as.POSIXct(as.Date(as.numeric(temps_f_min)), format="%H:%M:%S"), "%H:%M:%S")),
    ecart_prem = ifelse(is.na(as.Date(as.numeric(ecart_prem))), NA, 
                        format(as.POSIXct(as.Date(as.numeric(ecart_prem)), format="%H:%M:%S"), "%H:%M:%S"))
    )
```

```{r, echo = FALSE, warning = FALSE, message = FALSE}

df_triathlon %>%
  dplyr::select(-c(Cat, Classement, Total, cl_nat, rem_cyc, cl_cyc, rem_cap, cl_cap, ecart_prem)) %>%
  mutate(Type = ifelse(grepl("S", Type), "S",
                ifelse(grepl("M", Type), "M",
                ifelse(grepl("L", Type), "L", NA)))) %>% 
  group_by(Date, Course, Type) %>% summarise(Personne = toString(Nom)) %>% 
  arrange(desc(Date), Type) %>% 
  kbl() %>%
  kable_styling() 
```

<br>

Voici un graphique qui résumé nos classements :

```{r, include = FALSE}

plot <- df_triathlon %>% 
  filter(!grepl("Team", Type)) %>% 
  group_by(Nom, Type) %>% 
  summarise(Pourc = mean(Pourc, na.rm = TRUE), .groups = "drop") %>% 
  mutate(Type = factor(Type, levels = c("S", "M", "L"))) %>% 
  ggplot(aes(x = Pourc, y = Nom)) + 
  geom_col(aes(fill = Type), width = 0.5) + 
  theme_test() + 
  theme(strip.background = element_rect(fill = "white")) +
  scale_x_continuous(limits = c(0, 100)) + 
  labs(x = "Classement (en %)", y = "", fill = "Distance") + 
  scale_fill_manual(values = c("S" = "#24a69a", "M" = "#faa629", "L" = "#ed4a67")) + 
  facet_wrap(~Type) +
  geom_text(aes(x = 0, y = Nom, label = paste0(Pourc, "%")), hjust = -0.25, size = 3, color = "white")
```

```{r, echo = FALSE, warning = FALSE, message = FALSE}

print(plot)
```
