---
title: "Statistiques individuelles"
editor_options: 
  chunk_output_type: inline
---

```{r, include = FALSE}

library(readxl)
library(kableExtra)
library(tidyverse)
library(lubridate)

df_triathlon <- read_excel("links/triathlon.xlsx") %>%
  mutate(
    Pourc = ifelse(is.na(Pourc), NA, 
                   round(Pourc, 0)),
    t_nat = ifelse(is.na(t_nat), NA, 
                   format(as.POSIXct(t_nat, format="%H:%M:%S"), "%H:%M:%S")),
    all_nat = ifelse(is.na(all_nat), NA,
                     format(as.POSIXct(all_nat, format="%H:%M:%S"), "%H:%M:%S")),
    tran1 = ifelse(is.na(tran1), NA, 
                   format(as.POSIXct(tran1, format="%H:%M:%S"), "%H:%M:%S")),
    t_cyc = ifelse(is.na(t_cyc), NA, 
                   format(as.POSIXct(t_cyc, format="%H:%M:%S"), "%H:%M:%S")),
    all_cyc = ifelse(is.na(all_cyc), NA, 
                     round(all_cyc, 2)),
    tran2 = ifelse(is.na(tran2), NA,
                   format(as.POSIXct(tran2, format="%H:%M:%S"), "%H:%M:%S")),
    t_cap = ifelse(is.na(t_cap), NA, 
                   format(as.POSIXct(t_cap, format="%H:%M:%S"), "%H:%M:%S")),
    all_cap = ifelse(is.na(all_cap), NA, 
                     format(as.POSIXct(all_cap, format="%H:%M:%S"), "%H:%M:%S")),
    temps_f_min = ifelse(is.na(as.Date(as.numeric(temps_f_min))), NA, 
                        format(as.POSIXct(as.Date(as.numeric(temps_f_min)), format="%H:%M:%S"), "%H:%M:%S")),
    ecart_prem = ifelse(is.na(as.Date(as.numeric(ecart_prem))), NA, 
                        format(as.POSIXct(as.Date(as.numeric(ecart_prem)), format="%H:%M:%S"), "%H:%M:%S"))
    )
```

```{r, echo = FALSE, warning = FALSE, message = FALSE}

# Create a function to generate results and plot for each participant
generate_results_and_plot <- function(participant_name) {
  participant_data <- df_triathlon %>%
    filter(Nom == participant_name) %>%
    mutate(all_nat = as.numeric(hms(all_nat)))
    cat(paste0("## Résultats de ", participant_name, "\n\n"))
  
  # Generate and display the boxplot
  p <- ggplot(participant_data, aes(y = all_nat, x = Nom)) +
    geom_boxplot() +
    theme_test() +
    labs(title = paste("Boxplot of all_nat for", participant_name))
  
  print(p) 
  
  cat("\n\n")  
}

df_tri_name <- df_triathlon %>% filter(!grepl("Bergerie", Nom))
participant_names <- unique(df_tri_name$Nom)

for (name in participant_names) {
  generate_results_and_plot(name)
}
```
