---
title: "Les triathlons de La Bergerie"
lightbox: true
website:
  search: 
    location: navbar
    type: overlay
editor_options: 
  chunk_output_type: console
---

Voici le tableau récapitulatif de nos derniers triathlons :

```{r, include = FALSE}

library(readxl)
library(kableExtra)
library(tidyverse)

df_triathlon <- read_excel("tri/triathlon.xlsx") %>%
  filter(Pourc != "NA") %>% 
  filter(temps_f_min != "DNF") %>% 
  filter(all_cyc != "NA") %>%
  mutate(
    Pourc = ifelse(is.na(Pourc), NA, 
                   round(Pourc, 0)),
    t_nat = ifelse(is.na(t_nat), NA, 
                   format(as.POSIXct(t_nat, format="%H:%M:%S"), "%H:%M:%S")),
    all_nat = ifelse(is.na(all_nat), NA,
                     format(as.POSIXct(all_nat, format="%H:%M:%S"), "%H:%M:%S")),
    tran1 = ifelse(is.na(tran1), NA, 
                   format(as.POSIXct(tran1, format="%H:%M:%S"), "%H:%M:%S")),
    t_cyc = ifelse(is.na(t_cyc), NA, 
                   format(as.POSIXct(t_cyc, format="%H:%M:%S"), "%H:%M:%S")),
    all_cyc = ifelse(is.na(all_cyc), NA, 
                     round(as.numeric(all_cyc), 2)),
    tran2 = ifelse(is.na(tran2), NA,
                   format(as.POSIXct(tran2, format="%H:%M:%S"), "%H:%M:%S")),
    t_cap = ifelse(is.na(t_cap), NA, 
                   format(as.POSIXct(t_cap, format="%H:%M:%S"), "%H:%M:%S")),
    all_cap = ifelse(is.na(all_cap), NA, 
                     format(as.POSIXct(all_cap, format="%H:%M:%S"), "%H:%M:%S")),
    temps_f_min = ifelse(is.na(as.Date(as.numeric(temps_f_min))), NA, 
                        format(as.POSIXct(as.Date(as.numeric(temps_f_min)), format="%H:%M:%S"), "%H:%M:%S")),
    ecart_prem = ifelse(is.na(as.Date(as.numeric(ecart_prem))), NA, 
                        format(as.POSIXct(as.Date(as.numeric(ecart_prem)), format="%H:%M:%S"), "%H:%M:%S"))
    )
```

```{r, echo = FALSE, warning = FALSE, message = FALSE}

df_triathlon %>%
  dplyr::select(-c(Cat, Classement, Total, cl_nat, rem_cyc, cl_cyc, rem_cap, cl_cap, ecart_prem)) %>%
  mutate(Type = ifelse(grepl("S", Type), "S",
                ifelse(grepl("M", Type), "M",
                ifelse(grepl("L", Type), "L", NA)))) %>% 
  group_by(Date, Course, Type) %>% summarise(Personne = toString(Nom)) %>% 
  arrange(desc(Date), Type) %>% 
  kbl() %>%
  kable_styling() 
```

<br>

Voici un graphique qui résumé nos classements :

```{r, include = FALSE}

library(tidyverse)
library(readxl)

data_exploded <- df_triathlon %>%
  filter(grepl("Team", Type)) %>%
  mutate(Noms = str_extract(Nom, "\\((.*)\\)"),
         Noms = str_remove_all(Noms, "[\\(\\)]"),
         Noms = str_split(Noms, ",\\s*")) %>%
  unnest(Noms) %>%
  group_by(Nom) %>%
  mutate(Position = row_number()) %>%
  ungroup() %>%
  mutate(Nom = Noms) %>%
  dplyr::select(-Noms)

data_exploded <- data_exploded %>%
  mutate(across(contains(c("cyc", "cap", "tran")),
                ~ if_else(Position == 1, NA, .),
                .names = "{col}")) 

data_exploded <- data_exploded %>%
  mutate(across(contains(c("nat", "cap", "tran")),
                ~ if_else(Position == 2, NA, .),
                .names = "{col}"))

data_exploded <- data_exploded %>%
  mutate(across(contains(c("nat", "cyc", "tran")),
                ~ if_else(Position == 3, NA, .),
                .names = "{col}"))

data_exploded <- data_exploded %>%
  dplyr::select(-Position)

df_triathlon <- df_triathlon %>%
  filter(!grepl("Team", Type)) %>%
  rbind(data_exploded)

plot <- df_triathlon %>% 
  filter(Nom != "Mathis") %>%
  filter(Nom != "Antoine") %>% 
  mutate(Type =  ifelse(grepl("XS", Type), "XS",
                 ifelse(grepl("S", Type), "S",
                 ifelse(grepl("M", Type), "M",
                 ifelse(grepl("L", Type), "L",
                 ifelse(grepl("XL", Type), "XL", NA)))))) %>% 
  group_by(Nom, Type) %>% summarise(Pourc = mean(Pourc, na.rm = TRUE), .groups = "drop") %>% 
  mutate(Type = ifelse(Type %in% c("XS", "XS Team"), "XS", 
                       ifelse(Type %in% c("S", "S Team"), "S",
                              ifelse(Type %in% c("M", "M Team"), "M",
                                     ifelse(Type %in% c("L", "L Team"), "L",
                                            ifelse(Type %in% c("XL", "XL Team"), "XL", NA)))))) %>% 
  mutate(Type = factor(Type, levels = c("XS", "S", "M", "L", "XL"))) %>% 
  ggplot(aes(x = Pourc, y = Nom)) + 
  geom_col(aes(fill = Type), width = 0.5) + 
  theme_test() + 
  theme(strip.background = element_rect(fill = "white")) +
  scale_x_continuous(limits = c(0, 100)) + 
  labs(x = "Classement (en %)", y = "", fill = "Distance") + 
  scale_fill_manual(values = c("XS" = "lightblue", "S" = "#24a69a", "M" = "#faa629", "L" = "#ed4a67")) + 
  facet_wrap(~Type, ncol = 4) +
  geom_text(aes(x = 0, y = Nom, label = paste0(round(Pourc, 0), "%")), hjust = -0.25, size = 2.5, color = "white")
```

```{r, echo = FALSE, warning = FALSE, message = FALSE}

print(plot)
```
